name: daemon
channels:
  - conda-forge
dependencies:
  - cartopy = 0.21.1
  - dask = 2023.3.2
  - earthaccess = 0.5.2
  - geocube = 0.4.0
  - geopandas = 0.12.2
  - geoviews = 1.9.6
  - holoviews = 1.15.4
  - hvplot = 0.8.3
  - h5py = 3.8.0
  - iris = 3.4.1
  - matplotlib = 3.7.1
  - netcdf4 = 1.6.3
  - numpy = 1.23.5
  - pandas = 1.5.3
  - python = 3.10.10
  - rioxarray = 0.14.0
  - seaborn = 0.12.2
  - scikit-learn = 1.2.2
  - scipy = 1.10.1
  - spyder = 5.4.3
  - xarray = 0.21.0
  - xesmf = 0.7.0
  - yaml = 0.2.5
